Dbf reader
Neos1/fias-component pull request #5
Opened 2020-08-18 03:20 UTC by BayanValit

2020-10-01 06:45 UTC, coderNeos requested changes

2020-10-01 06:45 UTC, coderNeos commented on composer.json
> +    }
Вернуть репозитории, как в исходном файле

2020-10-01 06:45 UTC, coderNeos commented on src/FiasInformer/InformerResponse.php
> +     * @return string|false
Возвращаемое значение должно быть boolean

2020-10-01 06:45 UTC, coderNeos commented on src/FiasInformer/InformerResponseBase.php
> +        if ($this->validateUrl($url) === false) {
т.к. функция будет булева лучше использовать знак отрицания без строго сравнения с false

2020-10-01 06:45 UTC, coderNeos commented on src/FiasInformer/SoapFiasInformer.php
> +        $url = $res->validateUrl($response->GetLastDownloadFileInfoResult->$type_format);
Переписать моменты связанные с validateUrl с учётом изменений

2020-10-01 06:45 UTC, coderNeos commented on src/Pipeline/Task/InformFullTask.php
> +        $type = $state->getParameter(Task::DOWNLOAD_FILE_TYPE) ?? 'dbf';
Не надо задавать значения по умолчанию как dbf, нужно сделать как в предыдущем файле

2020-10-01 06:45 UTC, coderNeos commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +        $filesInfo = iterator_to_array($iterator);
лучше отсортировать результирующий массив перед return, чтобы не преобразовывать iterator к массиву

2020-10-01 06:45 UTC, coderNeos commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +        array_multisort($order, SORT_ASC, $filesInfo);
На мой взгляд здесь идеально подойдёт модификация сортировки вставкой

2020-10-01 06:45 UTC, coderNeos commented on src/Pipeline/Task/VersionSetTask.php
> +            $this->versionManager->setCurrentVersion($version, $size);
сделать отдельную функцию setCurrentSize, т.к. сейчас функция делает две вещи, а её название заявляет об одной

2020-10-01 06:45 UTC, coderNeos commented on src/Unpacker/ProcessUnpacker.php
> +    public function unpack(SplFileInfo $source, SplFileInfo $destination, array $files_to_extract = []): void
3 аргумент никак не используется - он не нужен?

2020-10-01 06:45 UTC, coderNeos commented on src/VersionManager/VersionManager.php
> +    public function setCurrentVersion(InformerResponse $info, $size): VersionManager;
убрать size отсюда

2020-10-01 12:19 UTC, BayanValit commented on src/Pipeline/Task/InformFullTask.php
> +        $type = $state->getParameter(Task::DOWNLOAD_FILE_TYPE) ?? 'dbf';
В предыдущей версии не предполагался выбор формата данных ФИАС для скачивания (был только xml). Удаление значения по умолчанию приведёт к тому, что параметр DOWNLOAD_FILE_TYPE придётся всегда явно указывать во время запуска artisan команд (INSTALL & UPDATE).

2020-10-01 13:20 UTC, BayanValit commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +        array_multisort($order, SORT_ASC, $filesInfo);
Артём, здесь не так просто поменять алгоритм сортировки. Тут логика сортировки построена на определении приоритетов обработки файлов. Здесь их 5. (от 0 до 4), причем в нулевом приоритете находится большая часть файлов и они не сортируются. Я считаю эту сортировку достаточно удачным решением, тем более гнаться за производительностью грубо говоря в сортировке 10 строк не вижу никакого смысла.

2020-10-01 13:28 UTC, BayanValit commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +        $filesInfo = iterator_to_array($iterator);
Сортировка в таком случае будет вызываться дважды - для массивов filesToInsert и filesToDelete.

2020-10-01 13:39 UTC, BayanValit commented on src/Pipeline/Task/VersionSetTask.php
> +            $this->versionManager->setCurrentVersion($version, $size);
Функция делает одно - заполняет строку версии ФИАС в таблице из 4 колонок (version, url, created_at, size). Вот не хотелось мне разделять этот процесс на 2 функции. Это нужно заполнить 3 столбца в таблице, сохранить, затем найти отдельным запросом эту строку по ключу version и вставить size.. - не то. Как насчет переименования функции на "setCurrentVersionData"?

2020-10-01 13:51 UTC, BayanValit commented on src/Unpacker/ProcessUnpacker.php
> +    public function unpack(SplFileInfo $source, SplFileInfo $destination, array $files_to_extract = []): void
Этот аргумент нужен чтобы распаковывать только те файлы, которые нам нужны. Здесь он действительно не нужен, но он есть т.к. используется в соседнем классе ZipUnpacker.php. Этот класс (ProcessUnpacker.php), как и соседний (ZipUnpacker.php) реализуют один и тот же интерфейс - Unpacker.php. Поэтому вот так. Как вариант можно этот параметр определить как опциональный (необязательный), тогда здесь можно будет его кикнуть.

2020-10-01 13:52 UTC, BayanValit commented on src/VersionManager/VersionManager.php
> +    public function setCurrentVersion(InformerResponse $info, $size): VersionManager;
Действие требует ответа на вопрос выше.

2020-10-01 13:56 UTC, BayanValit commented on src/FiasInformer/InformerResponse.php
> +     * @return string|false
ValidateUrl по совместительству ещё работал как getUrl(), конечно это косяк

2020-10-05 01:38 UTC, coderNeos commented on src/Pipeline/Task/InformFullTask.php
> +        $type = $state->getParameter(Task::DOWNLOAD_FILE_TYPE) ?? 'dbf';
тогда предлагаю использовать xml по умолчанию, как это и было изначально

2020-10-05 01:39 UTC, coderNeos commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +        $filesInfo = iterator_to_array($iterator);
дело в том, что у них по идее должна быть противоположная сортировка, т.к. в начале удалить адресные объекты не получится

2020-10-05 01:41 UTC, coderNeos commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +        array_multisort($order, SORT_ASC, $filesInfo);
Ок, это не критично

2020-10-05 01:44 UTC, coderNeos commented on src/Pipeline/Task/VersionSetTask.php
> +            $this->versionManager->setCurrentVersion($version, $size);
проблема в том, что InformerResponse относится к результату работы определенного класса, который не возвращает размер. Переименовать функцию не такая уж плохая идея, главное, чтобы было очевидно, что она делает. А вот как передать набор данных - тут надо подумать.

2020-10-05 01:45 UTC, coderNeos commented on src/Unpacker/ProcessUnpacker.php
> +    public function unpack(SplFileInfo $source, SplFileInfo $destination, array $files_to_extract = []): void
Параметр и так опциональный) Если ты его уберешь из интерфейса, то в нужном классе не получится его передать, т.к. реализация не будет соответствовать интерфейсу, оставляем так.

2020-10-05 01:45 UTC, coderNeos commented on src/VersionManager/VersionManager.php
> +    public function setCurrentVersion(InformerResponse $info, $size): VersionManager;
ответил

2020-10-21 15:51 UTC, BayanValit commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +        $filesInfo = iterator_to_array($iterator);
Нет, тут не нужна противоположная сортировка, так как файлы на удаление с префиксом 'D*' есть только у дельт, и они удаляются "мягко" - в дельта таблицах есть столбец delta type для этого. Противоположная сортировка действительно нужна при выполнении truncate команды, но это команда реализована в kric-fias и сортировка там не используется, так как я просто там выставил классы в нужном порядке для удаления.

2020-10-21 16:05 UTC, BayanValit commented on src/Pipeline/Task/VersionSetTask.php
> +            $this->versionManager->setCurrentVersion($version, $size);
Можно конечно сделать доп. поле в классе InformerResponse для size, но мне это не совсем нравится, потому это поле будет заполняться в отдельной задаче распаковки, и получится некая неоднородность. 
Лепить массив из (InformerResponse объект + integer $size) - тоже, такое себе. Может, всё-таки, переименовать и оставить как есть?

2020-10-22 03:35 UTC, coderNeos requested changes

2020-10-22 03:35 UTC, coderNeos commented on src/FiasInformer/SoapFiasInformer.php
> +                throw new InvalidArgumentException("Unsupported required type: \"{$type}\"");
почему выбрал такое сообщение: "required type"?

2020-10-22 03:35 UTC, coderNeos commented on src/FiasInformer/SoapFiasInformer.php
> +        if ($res->validateUrl($url)) {
тут меняется поведение, раньше выдавалась ошибка, теперь её не будет. Нужно просто вызвать setUrl

2020-10-22 03:35 UTC, coderNeos commented on src/FiasInformer/SoapFiasInformer.php
> +            if ((int) $serviceVersion['VersionId'] <= $version || !$res->validateUrl($url)) {
Аналогично предыдущему

2020-10-22 03:35 UTC, coderNeos commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +        return [$this->sortFilesInfo($filesToInsert), $this->sortFilesInfo($filesToDelete)];
для файлов на удаление нужна противоположная сортировка, надо учитывать, что это публичная библиотека, и не факт, что у кого то будет реализовано мягкое удаление как у нас

2020-10-22 03:35 UTC, coderNeos commented on src/Pipeline/Task/VersionSetTask.php
> +        $version_data = $state->getParameter(Task::FIAS_INFO_PARAM);
Как-то коряво выходит, давай сделаем отдельную задачу SizeSetTask, а этот код вернем к исходному

2020-10-22 12:22 UTC, BayanValit commented on src/FiasInformer/SoapFiasInformer.php
> +            if ((int) $serviceVersion['VersionId'] <= $version || !$res->validateUrl($url)) {
Здесь хочу отметить, что использование validateUrl() уместно тем, что оно не выбрасывает исключение в отличие от setUri(). Это сделано потому что при получении ссылки с сервиса обновления ФИАС вполне вероятна ситуация когда на сервисе есть ссылка на формат обновления xml, а на dbf его нет - при этом version_id будет успешно заполнен, а ссылка на url = ''.  Бросать исключение при этом я не хотел, и поэтому эта версия обновления просто пропускалась, оставаясь на предпоследней позиции.

2020-10-22 13:10 UTC, BayanValit commented on src/Pipeline/Task/VersionSetTask.php
> +        $version_data = $state->getParameter(Task::FIAS_INFO_PARAM);
Отдельная задача уже есть, которая высчитывает этот размер, и записывает результат в параметр, можно переделать логику так, чтобы сначала заполнялась version_id, url, created_data, а затем добавлялся size. Сейчас сделано так: получаем данные о версии и url, загружаем, распаковываем, затем подсчитываем размер архива, затем вставляем всё в БД, и только потом устанавливаем данные о версии целиком version + size. В принципе можно вставлять отдельно size после установки версии. Эти изменения будут касаться репозитория kric-fias.

2020-10-23 05:53 UTC, coderNeos requested changes

2020-10-23 05:53 UTC, coderNeos commented on src/FiasInformer/SoapFiasInformer.php
> +            if ((int) $serviceVersion['VersionId'] <= $version || !$res->validateUrl($url)) {
Это понятно, но речь здесь идёт о том какое поведение было у библиотеки раньше. Если мы это изменим, то код, который зависел от данного участка сломается. И здесь есть проблема следующего характера: если получится, что по какой-то причине версия пропущена, произойдет некорректное обновление, потому я считаю, что нужно выкидывать исключение. Его обработка должна быть на верхнем уровне, т.е. в приложении.

2020-10-23 05:53 UTC, coderNeos commented on src/Pipeline/Task/SelectFilesToProceedTask.php
> +use phpDocumentor\Reflection\Types\Boolean;
Ошибка?

2020-10-23 05:53 UTC, coderNeos commented on src/VersionManager/VersionManager.php
> +
Пустая строка

2020-10-23 05:53 UTC, coderNeos commented on src/Pipeline/Task/VersionSetTask.php
> +        $version_data = $state->getParameter(Task::FIAS_INFO_PARAM);
Да, отлично, так и сделаем

2020-10-23 06:41 UTC, coderNeos approved these changes

2020-10-23 06:41 UTC, merged